# Generated by Django 4.2.4 on 2023-08-28 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_groups_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Ensure username has at least 2 characters (it has 1).')]),
        ),
    ]
