# Generated by Django 4.2.4 on 2023-08-28 13:37

import audio_to_text.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', audio_to_text.accounts.managers.AppUserManager()),
            ],
        ),
    ]
