# Generated by Django 4.2.4 on 2023-08-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='extracted_text',
            field=models.CharField(blank=True, null=True),
        ),
    ]
