# Generated by Django 4.2.4 on 2023-08-30 10:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audio_extracted_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='audios', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
