# Generated by Django 4.2.4 on 2023-08-30 10:57

import audio_to_text.audio.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_remove_audio_audio_audio_audio_file_audio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to=audio_to_text.audio.models.unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])]),
        ),
    ]
