# Generated by Django 4.2.4 on 2023-09-02 17:49

import audio_to_text.photos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo_file', models.ImageField(upload_to=audio_to_text.photos.models.unique_filename)),
                ('date_of_upload', models.DateTimeField(auto_now=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('eng', 'English'), ('bul', 'Bulgarian'), ('deu', 'German')], max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
