# Generated by Django 4.2.4 on 2023-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('bul', 'Bulgarian'), ('deu', 'German')], max_length=9),
        ),
    ]
