# Generated by Django 4.2.4 on 2023-08-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='language',
            field=models.CharField(choices=[('English', 'eng'), ('Bulgarian', 'bul')], default=2),
            preserve_default=False,
        ),
    ]
