# Generated by Django 4.2.4 on 2023-09-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='word_document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
