# Generated by Django 4.2.4 on 2023-08-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('bul', 'Bulgarian'), ('deu', 'German')]),
        ),
    ]
