# Generated by Django 4.2.4 on 2023-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audio_extracted_text_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='word_document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
